version: "3.8"

services:
  redis-cache:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env